Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  # Для повільних ПК/першого старту
  config.vm.boot_timeout = 1800

  # ENV з Windows PowerShell
  db_user = ENV["DB_USER"] || "petuser"
  db_pass = ENV["DB_PASS"] || "petpass123"
  db_name = ENV["DB_NAME"] || "petclinic"

  # -----------------------
  # DB VM
  # -----------------------
  config.vm.define "DB_VM" do |db|
    db.vm.hostname = "db-vm"
    db.vm.network "private_network", ip: "192.168.56.10"

    db.vm.provider "virtualbox" do |vb|
      vb.name = "DB_VM"
      vb.memory = 1024
      vb.cpus = 1
    end

    db.vm.provision "shell",
      path: "provision/db.sh",
      env: {
        "DB_USER" => db_user,
        "DB_PASS" => db_pass,
        "DB_NAME" => db_name,
        "DB_BIND_IP" => "192.168.56.10"
      }
  end

  # -----------------------
  # APP VM
  # -----------------------
  config.vm.define "APP_VM" do |app|
    app.vm.hostname = "app-vm"
    app.vm.network "private_network", ip: "192.168.56.20"

    # Доступ з Windows: http://localhost:8080
    app.vm.network "forwarded_port", guest: 8080, host: 8080

    app.vm.provider "virtualbox" do |vb|
      vb.name = "APP_VM"
      vb.memory = 2048
      vb.cpus = 2
      # якщо знов буде таймаут — постав true щоб показувати вікно ВМ і дивитися що там відбувається
      vb.gui = true
    end

    app.vm.provision "shell",
      path: "provision/app.sh",
      env: {
        "APP_USER" => "appuser",

        "DB_HOST" => "192.168.56.10",
        "DB_PORT" => "3306",
        "DB_NAME" => db_name,
        "DB_USER" => db_user,
        "DB_PASS" => db_pass,

        # твій репо
        "REPO_URL" => "https://github.com/Di0Geen/dan-it-devops-13-practice.git",

               
        "PROJECT_SUBDIR" => "Homework/HomeworkStepProject/spring-petclinic"
      }
  end
end