{
 "title": "cAdvisor Docker Containers - macOS",
 "description": "Grafana community dashboard 21743 adapted for Docker Desktop cgroup id labels.",
 "tags": [
  "cadvisor",
  "docker"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "docker_host",
    "label": "Docker Host",
    "query": {
     "query": "label_values({__name__=~\"container.*\"},instance)"
    }
   },
   {
    "name": "container_id",
    "label": "Container cgroup",
    "query": {
     "query": "label_values({__name__=~\"container.*\", instance=~\"$docker_host\", id!=\"/\"},id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage (% by Core)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{instance=~\"$docker_host\",id=~\"$container_id\",id!=\"/\"}[10m])) by (id) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage by Instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{instance=~\"$docker_host\",id!=\"/\"}) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{instance=~\"$docker_host\",id=~\"$container_id\",id!=\"/\"}) by (id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Cached",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_cache{instance=~\"$docker_host\",id=~\"$container_id\",id!=\"/\"}) by (id)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "I/O", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Reads",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{instance=~\"$docker_host\",id=~\"$container_id\",id!=\"/\"}[10m])) by (id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Writes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{instance=~\"$docker_host\",id=~\"$container_id\",id!=\"/\"}[10m])) by (id)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Received Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{instance=~\"$docker_host\",id=~\"$container_id\",id!=\"/\"}[10m])) by (id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sent Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{instance=~\"$docker_host\",id=~\"$container_id\",id!=\"/\"}[10m])) by (id)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Container Restarts",
   "type": "heatmap",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "count by(id) (count_over_time(container_last_seen{instance=~\"$docker_host\",id=~\"$container_id\",id!=\"/\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}